# Generated by Django 5.2.11 on 2026-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
    ]
